version: '3.8'

services:
  spring:
    image: openjdk:17-jdk-slim
    env_file:
      - backend.env
    volumes:
      - ./build/libs/backend-0.0.1-SNAPSHOT.jar:/app/backend/app.jar
    command: [ "java","-jar","/app/backend/app.jar" ]
    container_name: spring
    ports:
      - "8080:8080"

