version: '3.8'

services:
  spring:
    env_file:
      - backend.env
    volumes:
      - ./build/libs/backend-0.0.1-SNAPSHOT.jar:/app/backend/app.jar
    command: [ "java","-jar","/app/backend/app.jar" ]
    container_name: spring
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_HIBERNATE_DIALECT: ${SPRING_JPA_HIBERNATE_DIALECT}
      JWT_SECRET: ${JWT_SECRET}
      GITLAB_APPLICATION_ID: ${GITLAB_APPLICATION_ID}
      GITLAB_REDIRECT_URI: ${GITLAB_REDIRECT_URI}
      GITLAB_CLIENT_SECRET: ${GITLAB_CLIENT_SECRET}
      GITLAB_API_BASE_URL: ${GITLAB_API_BASE_URL}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
      FIREBASE_CONFIG_PATH: ${FIREBASE_CONFIG_PATH}
      DOCKER_HUB_BASE_URL: ${DOCKER_HUB_BASE_URL}
      DOCKER_TOKEN_PREFIX: ${DOCKER_TOKEN_PREFIX}
      DOCKER_REGISTRY_BASE_URL: ${DOCKER_REGISTRY_BASE_URL}
      DOCKER_AUTH_BASE_URL: ${DOCKER_AUTH_BASE_URL}
      FILE_BASE_PATH: ${FILE_BASE_PATH}
      LOGGING_LEVEL_REACTOR_NETTY_HTTP_CLIENT: ${LOGGING_LEVEL_REACTOR_NETTY_HTTP_CLIENT}
      LOGGING_LEVEL_EXCHANGEFUNCTIONS: ${LOGGING_LEVEL_EXCHANGEFUNCTIONS}
      LOGGING_LEVEL_ORG_EXAMPLE_BACKEND: ${LOGGING_LEVEL_ORG_EXAMPLE_BACKEND}
      JENKINS_API_BASE_URL: ${JENKINS_API_BASE_URL}
      JENKINS_USERNAME: ${JENKINS_USERNAME}
      JENKINS_API_TOKEN: ${JENKINS_API_TOKEN}
      JENKINS_JOB_NAME: ${JENKINS_JOB_NAME}